[package]
name = "validate_json"
version = "0.12.0"
edition = "2021"

[workspace]

[dependencies]
json = "0.12"
json-core = { path = "../../core" }
risc0-zkvm = { version = "2.0.0", default-features = false, features = ["std"] }

